# Generated by Django 4.1.7 on 2023-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.IntegerField(unique=True),
        ),
    ]
